<?php
	$all = [
		[
			"name"=>"Baked Mac & Cheese", 
			"img"=>"image tbd", 
			"intro"=>["Back when I was a kid, my great grandmother would make this incredible mac &amp; cheese. It was so good that I would swear it was the best mac in the world. In fact, I <em>still</em> think that it's the best mac in the world. Whenever I make it, I'm mentally transported back to the Silent House, down in Key Biscayne.", "Not only is this dish the most prominent one in my mind when I think of Rosie's cooking, it's also the first recipe of hers that I ever made myself. I was surprised at how easy it was, and how much I could really mess around with it. I could never really perfectly replicate it; there's just something special to it that only Grandma Rosie could do. This recipe is as close as I could really get to capturing that magic."], 
			"ingredients"=>["1 pound of pasta - any kind works, but for best results I suggest either penne or macaroni.", "1 pound of shredded cheese - I recommend sharp cheddar, but this is entirely up to your taste.", "1 stick of butter", "1 cup of milk", "4 eggs"], 
			"procedure"=>["First, cook the pasta. You want it to be fairly al dente since it's going to be cooked more later, and for many varieties of pasta this means no more than five minutes of cook time. Once it's done, set it aside in a colander to drain and cool.", "While the pasta is cooling, take the eggs and crack them into a medium-sized bowl. Beat them together with a fork, and mix in the milk.", "Next, chop up the stick of butter into small chunks, and add them into the egg/milk mixture. It will be chunky and might clump together a bit, but don't worry!", "Once your pasta is cool enough that it won't cook the eggs on contact, move it into a large mixing bowl and pour the egg/milk/butter mixture in. Mix it around until the chunks of butter seem to be evenly distributed, at which point you should add about half of the shredded cheese.", "After you finish mixing the cheese in, grease a 9x13 casserole pan with butter, and pour the pasta into it. Spread it out so that the surface is fairly flat, and then put the rest of the cheese on top", "Season the top with salt and pepper, and then place in a 350 degree oven for 30-40 minutes. You'll know it's done when the top looks nice and crispy."]
		],
		[
			"name"=>"Peach Cobbler", 
			"img"=>"image tbd", 
			"intro"=>["This is one of the recipes that I didn't even know Grandma Rosie made. Looking back, I can't actually remember having it before I made it myself in my apartment. That said, I called her not long after making it to talk with her about cobblers and how to make them.", "During that conversation, Rosie told me that this recipe works well with pretty much any fruit, and that frozen fruit is the best. Of course, you need to defrost it first, but once that's done, it often works better than fresh fruit in a cobbler. She also suggested that the next time I make a cobbler, I should try it with blueberries and apple slices."], 
			"ingredients"=>["1 stick of butter", "1 cup of sugar", "1 cup of flour", "2 teaspoons of baking powder", "2/3 of a cup of milk", "1 egg", "2 cups of peaches - fresh or frozen ideally, but canned will work", "4 more tablespoons of sugar, to sprinkle on top", "Cinnamon"], 
			"procedure"=>["Start off by putting the stick of butter into a 9x9 pan. Place that into your oven as you preheat it to 375 degrees, and check it every once in a while until it is thoroughly melted.", "While the butter is melting, put together the batter. Mix the sugar, flour, baking powder, milk, and egg together in a medium-sized bowl until they are fairly smooth.", "Once the butter is done melting, take it out of the oven and pour the batter into it. <em>Do not mix this.</em> Instead, let it sit for a few minutes, until the butter rises up around the batter, fully submerging it.", "Next, add the peaches. Let them sink in until they are fully submerged.", "Once that's done, sprinkle the additional 4 tablespoons of sugar over the top of the mixture with a bit of cinnamon.", "Finally, place the cobbler into the oven, baking it for 45 minutes at 375 degrees."]
		],
		[
			"name"=>"Grandma Ann's Hamentashen", 
			"img"=>"https://lh3.googleusercontent.com/ObrTkJtP-IlxcMCKmTxUC4spQhWmdcmQABveJzM_644JvYWIZs_d5vqKtGSSBmDc4sKHi2nWUxqBnS5lgqp5Vw30bjNyRJmiglHfiLYw6C0OgF7vrQcEF8fJQQW5f2xNasn2qqurMfZxEqi3YjOGTQF9d3I-MnH5R5l_oc1u5w-WQzXA_fa9LhR5XBvETn9MufvhM5SS0DEjbGgNes0GWq55bJwEYygYvgI76tb7s7pnBQIX_gJPap-mAiZhHtDxeHUtiswmVndwc2Lu__AKAjh23_VvTpHlDI3oRXKyUHZZWlPBQdLL8-LtsLF8xLh90LIzU-vznyHFf8wxxDajJ9zXENEgW5Glf5cyIe_p3chNNBTb19diHK4MQ3354AJx8h8LmliBuo67bE3pwzR2O7ATzXo4hItFDc6t_ebKHley-eZ_wfV_Avz0I7xdCKPWIH6l3TK6Mw0jlTyDaEWWNJEynzY-sw-S0N7ypL9onCYY04lA6hjUbSFHS_aGuIHpmydsjf-9aWpgijBZFMbwr0b_H5hZwHGzOZvNzsKO9LrXK1WhF1Zj-8EM-LSmAVgAq9LKPk4KBdG1_UILJbUpP7tYbsYzVQ07lRXqmkqh1pL9aIdNwIkZYWmJhZCMCTVmjgEqBjkwPvsZlEkG15c3k8AF_ynpq9j15EsROADlSd2xB4cr_YjCbhcB=s977-no", 
			"intro"=>["I never knew my great-great-grandmother, but I suppose she's been a part of my life since I was small. Back when I was a kid, my family would often travel down to Florida to be with family around Purim. Purim, for those who don't know, is a Jewish holiday celebrating deliverance from annihilation at the hands of the Persian empire. A common part of the holiday is the consumption of Hamentashen, three-pointed pastries that are usually filled with some sort of jelly or jam.", "While we were in Florida, my siblings and I would spend time in Grandma Rosie's kitchen, making these pastries. She taught us everything: How to pinch the corners just right so the dough wouldn't fall apart, how much filling to put in the middle, how to roll the dough flat and cut circles out of it... I didn't know it at the time, but the recipe that she used was the same recipe her mother used, and I think it's an honor to be able to pass it on to the next generation."], 
			"ingredients"=>["2 and a half cups of flour", "2 teaspoons of baking powder", "1 teaspoon of salt", "1/2 cup of sugar", "2 eggs", "1/2 cup of butter", "1 teaspoon of lemon juice", "2 pounds of pitted prunes", "1/4 cup of sugar, for the filling", "1/4 cup of orange juice"], 
			"procedure"=>["First, make the filling. This recipe will make enough for about three batches of dough. Start off by soaking the prunes in hot water for 30 minutes.", "Drain the water, and then mash the prunes into a paste before mixing in 1/4 of a cup of sugar.", "Next, mix in the orange juice, cover the mixture, and place it in the fridge to cool.", "Now that the filling is out of the way, it's time to make some dough! Start off by softening the butter a bit before mixing it with the rest of the sugar in a large bowl.", "Once the butter and sugar are thoroughly mixed, start to add the eggs. Crack them in one at a time, mixing each one in thoroughly before adding the next.", "Add in the baking powder and lemon juice and mix thoroughly before adding in the flour. Continue to stir the mixture until it starts to form into a doughy mass.", "At this point, you should switch from stirring the mixture to kneading it with your hands, since that'll make it easier to work with. Knead until there is little to no flour left in the mixing bowl.", "Cover a clean, flat surface like a cutting board or your countertop with a light dusting of flour, and place your dough on top. Roll it flat, until it's about a centimeter thick.", "Next, cut out as many 3-4 inch wide circles from it as you can.", "Take a small spoonful of filling and place it in the center of one circle. Then, fold the sides up in a triangle around it and pinch the corners shut. Repeat this process for each circle that you've cut out.", "Take whatever dough you have left, roll it into a ball, and then flatten it back out. Repeat these last few steps until you run out of dough, which should result in 14-16 Hamentashen.", "Place the newly-formed Hamentashen on a baking sheet, and give them a light egg wash. To do this, beat an egg in a small bowl, and then lightly brush the egg on the sides of the pastry.", "Finally, place the tray in a 375 degree oven for 20-25 minutes."]
		], 
		[
			"name"=>"Banana Bread",
			"img"=>"https://lh3.googleusercontent.com/pw/ACtC-3dhmGIwGTVETE74gbnG0Yv-4kUwcFLdmetYGg6k6WMnV-B3Ry0isBGMTWNpCnuxr1SXWDHdEBMJD2fmhuasv3LQAIO7iuequ4GEiOLqr7Zj_Qz3z6LADFnNf7gjr0xLJ8JYKFzmWgdEcADFoFblpUZ0kw=w1346-h1009-no?authuser=0",
			"intro"=>["Banana bread is something that recently re-entered my life, when my roommates and I bought some bananas and then proceeded to forget about them for about a week. At the time, I didn't have this recipe, or any of Grandma Rosie's recipes for that matter, so I used a recipe that I found online. I ended up using that recipe a lot, since my roommates and I all really enjoyed it. Once school starts back up, I'm going to start using this recipe instead - it's a lot better."],
			"ingredients"=>["1 stick of butter", "1 cup of sugar", "1 egg", "1 teaspoon of baking soda, dissolved in 1 tablespoon of water", "1 teaspoon of vanilla extract", "1 cup of mashed bananas - I find that this is generally 3-4 bananas.", "1 and a half cups of flour", "A dash of salt", "Some cinnamon", "Nuts, raisins, chocolate chips - take your pick!"],
			"procedure"=>["In a large bowl, cream the butter and sugar together. It's easiest to do this if you soften the butter first, so that you can get a fairly even mixture.", "Beat in an egg, mixing thoroughly before adding in your baking soda/water mix.", "Next, add the vanilla extract and salt. Keep mixing!", "If you haven't yet mashed your bananas, do that now, and then add them into the mix along with however much cinnamon you think feels right. I generally put about a teaspoon in.", "Now that all of the \"wet\" ingredients are mixed, add in the flour and mix well, until there isn't any evidence of flour in the bowl and everything has come together into a fairly thick batter.", "At this point, consider what you want to add to this banana bread. I recommend mixing in chocolate chips or walnuts, or even both, if you're feeling bold.", "Finally, pour the mixture into a loaf pan and bake it at 350 degrees for 50 minutes to an hour, or until a toothpick poked into the center of the loaf comes out clean."]
		]
	];
	
	function deChunk($chunk, $wrapper) {
		for ($i = 0; $i < count($chunk); $i++) {
			echo "<".$wrapper.">".$chunk[$i]."</".$wrapper.">";
		}
	}
	
	function alphaSort($a, $b) {
		return strcasecmp($a["name"], $b["name"]);
	}
	
	function displayAll($arr) {
		for($i = 0; $i < count($arr); $i++) {
			$name = $arr[$i]["name"];
			echo "<p><a href='recipe.php?recipe=".rawurlencode($name)."'>".$name."</a></p>";
		}
	}

	usort($all, 'alphaSort');
?>